### ISSUE TITLE
Needs to return `null` in case if path is not contain tilde

### ISSUE THREAD

**Issue by ViieeS** [matthewdavidson/node-sass-tilde-importer#6]
https://github.com/sass/node-sass#importer--v200---experimental
> importer can be an array of functions, which will be called by LibSass in the order of their occurrence in array. This helps user specify special importer for particular kind of path (filesystem, http). If an importer does not want to handle a particular path, it should return null.

**Comment by tadam313** [comment]
👋 @ViieeS, thanks for the contribution, this is a good point, I'll take a look at the PR.
